---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
  labels:
    app: grafana
  name: grafana
spec:
  ports:
  - name: web-proxy
    port: 3000
    protocol: TCP
    targetPort: web-proxy
  selector:
    app: grafana
  type: ClusterIP

